// test/llm-ollama.test.js
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { planFromPrompt, debugFailure } from '../src/llm-ollama.js';

test('llm-ollama: planFromPrompt with mocked fetchFn', async (t) => {
  await t.test('parses plan generated by local Ollama server', async () => {
    const mockFetch = async (url, options) => {
      assert.match(url, /\/api\/generate$/);
      const body = JSON.parse(options.body);
      assert.equal(body.model, 'qwen2.5-coder');
      assert.equal(body.format, 'json');

      return {
        status: 200,
        text: async () =>
          JSON.stringify({
            response: '{"summary": "Ollama Plan", "steps": [{"description": "Say Hello", "command": "echo hello"}]}',
          }),
      };
    };

    const plan = await planFromPrompt('create a hello world', { fetchFn: mockFetch });
    assert.equal(plan.summary, 'Ollama Plan');
    assert.equal(plan.steps.length, 1);
    assert.equal(plan.steps[0].command, 'echo hello');
  });

  await t.test('handles ECONNREFUSED connection error with actionable instructions', async () => {
    const mockFetch = async () => {
      const err = new Error('fetch failed');
      err.code = 'ECONNREFUSED';
      throw err;
    };

    await assert.rejects(
      async () => {
        await planFromPrompt('create app', { fetchFn: mockFetch });
      },
      (err) => {
        assert.match(err.message, /Ollama server is not running or unreachable/);
        assert.match(err.message, /ollama serve/);
        assert.match(err.message, /https:\/\/ollama\.com/);
        return true;
      }
    );
  });

  await t.test('handles 404 model not found error with ollama pull instructions', async () => {
    const mockFetch = async () => ({
      status: 404,
      text: async () => JSON.stringify({ error: 'model "qwen2.5-coder" not found' }),
    });

    await assert.rejects(
      async () => {
        await planFromPrompt('create app', { fetchFn: mockFetch });
      },
      (err) => {
        assert.match(err.message, /Ollama model "qwen2.5-coder" was not found/);
        assert.match(err.message, /ollama pull qwen2.5-coder/);
        return true;
      }
    );
  });
});

test('llm-ollama: debugFailure with mocked fetchFn', async (t) => {
  await t.test('parses diagnosis generated by local Ollama server', async () => {
    const mockFetch = async () => ({
      status: 200,
      text: async () =>
        JSON.stringify({
          response: '{"diagnosis": "Missing file", "fixedCommand": "touch index.js"}',
        }),
    });

    const debug = await debugFailure('node index.js', 'ENOENT', { fetchFn: mockFetch });
    assert.equal(debug.diagnosis, 'Missing file');
    assert.equal(debug.fixedCommand, 'touch index.js');
  });
});
